name: wedding_day_invite
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8

  go_router: ^14.7.2
  gap: ^3.0.1
  intl: ^0.20.2
  url_launcher: ^6.3.1
  audioplayers: ^6.1.1
  flutter_animate: ^4.5.2
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.17
  file_picker: ^9.0.0
  carousel_slider: ^5.0.0
  webview_flutter_web: ^0.2.3+4
  youtube_player_flutter: ^9.1.1
  flutter_gen: ^5.9.0
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.0.0
  shared_preferences: ^2.5.2

  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.9.0
  build_runner: ^2.4.15

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/gif/
    - assets/svg/
    - assets/music/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 
  fonts:
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes.ttf

    - family: LucySaid
      fonts: 
        - asset: assets/fonts/LucySaid.ttf
    - family: Ananda
      fonts: 
        - asset: assets/fonts/Ananda.ttf
    - family: Geraldine
      fonts: 
        - asset: assets/fonts/Geraldine.ttf
    - family: Weather
      fonts: 
        - asset: assets/fonts/Weather.otf
    - family: Dancing
      fonts: 
        - asset: assets/fonts/Dancing.ttf
    - family: Rolling
      fonts: 
        - asset: assets/fonts/Rolling.ttf
    - family: Coneria
      fonts: 
        - asset: assets/fonts/Coneria.ttf

  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package


flutter_gen:
  output: lib/gen
  line_length: 120

  integrations:
    flutter_svg: true
